# Generated by Django 4.0.6 on 2022-07-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_optcode_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPTCode',
            new_name='OTPCode',
        ),
    ]
