# Generated by Django 4.0.6 on 2022-07-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authority',
            field=models.CharField(default='test', max_length=250, verbose_name='کد پرداخت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='کد رهگیری'),
        ),
    ]
